name: doodleblue_task
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  collection: ^1.17.1
  connectivity_plus: ^5.0.2
  dio: ^5.4.3+1
  envied: ^0.5.4+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_easyloading: ^3.0.5
  flutter_screenutil: ^5.9.3
  http: ^1.1.0
  logger: ^2.3.0
  map_launcher: ^3.2.0
  shimmer: ^3.0.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.9
  mockito: ^5.4.2
  bloc_test: ^9.1.7
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
